xorg-app-xinit: merge updates from PLD

diff --git a/xorg-app-xinit/xorg-app-xinit-Xclients b/xorg-app-xinit/xorg-app-xinit-Xclients
--- a/xorg-app-xinit/xorg-app-xinit-Xclients
+++ b/xorg-app-xinit/xorg-app-xinit-Xclients
@@ -5,58 +5,82 @@ syswmfile="/etc/sysconfig/desktop"
 
 # Default values - may be redefined in $syswmfile
 userwmfile=".desktop"
-wmstyledir="/etc/sysconfig/wmstyle"
 xsessdir="/usr/share/xsessions"
 DEFAULTWM=""
 
 # Unset these
 unset USERWM WM_CHOICE
 
-load_session() {
-    if test `/usr/bin/which $WM_CHOICE 2>/dev/null`; then
-	eval "exec $WM_CHOICE"
-    fi
+loadsess()
+{
+	typeset runwm=$1
+
+	[ -z "$runwm" ] && return
+
+	if [ -x "$HOME/bin/$runwm.sh" ]; then
+		exec "$HOME/bin/$runwm.sh"
+	elif test `/usr/bin/which $runwm 2>/dev/null`; then
+		eval "exec $runwm"
+	fi
+}
+
+findxsession()
+{
+	typeset -l __XSESSION=$1
+	typeset f progname=""
+
+	if [ ! -d "$xsessdir" ]; then
+		echo "$xsessdir not found - check Your settings." >&2
+		return
+	fi
+	for f in $xsessdir/*.desktop; do
+		typeset -l sessfile sessname altnames
+		sessfile=$(basename $f .desktop)
+		sessname=$(grep "^Name=" $f)
+		sessname=${sessname##name=}
+		if [ "$sessname" = "$__XSESSION" -o "$sessfile" = "$__XSESSION" ]; then
+			progname=$(grep "^Exec=" $f)
+			progname=${progname##Exec=}
+			break
+		fi
+		altnames=$(grep "^X-AltNames=" $f)
+		altnames=${altnames##x-altnames=}
+		oldIFS=$IFS ; IFS=";"; set -- $altnames ; IFS=$oldIFS
+		altnames="$*" 
+		for n in $altnames; do
+			if [ "$n" = "$__XSESSION" ]; then
+				progname=$(grep "^Exec=" $f)
+				progname=${progname##Exec=}
+	    			break 2
+			fi
+		done
+	done
+	echo $progname
 }
 
 [ -f $syswmfile ] && . $syswmfile
 
 userwmfilefp=$HOME/$userwmfile
 
-[ -f $userwmfilefp ] && USERWM=`cat $userwmfilefp |grep -v ^# |head -n 1`
+[ -f $userwmfilefp ] && USERWM=`grep -v "^#" $userwmfilefp | head -n 1`
 
 # Evaluate cmdline first
 [ -n "$*" ] && USERWM="$*"
 
 if [ -n "$USERWM" ]; then
-        # Tray to run literal user choice first
-	WM_CHOICE=$USERWM
-	load_session
+        # Try to run literal user choice first
+	loadsess $USERWM
 	# if it fails - take another actions
-	WM_CHOICE=""
-	if [ ! -d "$xsessdir" ]; then
-		echo "$xsessdir not found - check Your settings."
-		exit 1
+	WM_CHOICE=$(findxsession $USERWM)
+	if [ -n "$WM_CHOICE" ]; then
+		loadsess $WM_CHOICE
 	fi
-	for f in $xsessdir/*.desktop; do
-		if [ "`cat $f |grep ^Name= |sed -e 's/Name=//' |tr A-Z a-z`" = "`echo $USERWM |tr A-Z a-z`" ]; then
-			WM_CHOICE=`cat $f |grep ^Exec= |sed -e 's/Exec=//'`
-			break
-		fi
-		for g in `cat $f |grep ^X-AltNames= |sed -e 's/X-AltNames=//' -e 's/;/ /g'`; do
-			if [ "`echo $g |tr A-Z a-z`" = "`echo $USERWM |tr A-Z a-z`" ]; then
-	    			WM_CHOICE=`cat $f |grep ^Exec= |sed -e 's/Exec=//'`
-	    			break 2
-			fi
-		done
-	done
-	if [ -z "$WM_CHOICE" ]; then
-		echo "Sorry - nothing known about $USERWM"
-		echo "Resuming with system defaults..."
-		WM_CHOICE=$DEFAULTWM
-	fi
-else
-        WM_CHOICE=$DEFAULTWM
+	echo "Sorry - nothing known about $USERWM" >&2
+	echo "Resuming with system defaults..." >&2
 fi
 
-[ -n "$WM_CHOICE" ] && load_session || exec urxvt
+WM_CHOICE=$(findxsession $DEFAULTWM)
+
+loadsess $WM_CHOICE
+exec urxvt
 
